# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'EOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'naveridlogin-sdk-ios'

  # Pods for EOD

  target 'EODTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EODUITests' do
    # Pods for testing
  end

end

target 'Preview EOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Preview EOD

end
